# dependencies

FROM node:22-alpine AS deps

WORKDIR /app
COPY package.json package-lock.json* ./

RUN npm ci


# builder
FROM node:22-aplin AS builder

WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules

COPY . .

RUN npm run build

# runner

FROM node:22-alpine AS runner

WORKDIR /app

RUN addgroup --system -gid 1001 nodejs
RUN adduser --system --uid 1001 nodejs

COPY package.json package-lock.json* ./
RUN npm ci --only=production

COPY --from=builder --chown=nodejs:nodejs /app/dist ./dist

USER nodejs

EXPOSE 3000

CMD ["node","dist/main.js"]